! HiPart is a software toolkit to analyse molecular densities with the hirshfeld partitioning scheme.
! Copyright (C) 2007 - 2010 Toon Verstraelen <Toon.Verstraelen@UGent.be>
!
! This file is part of HiPart.
!
! HiPart is free software; you can redistribute it and/or
! modify it under the terms of the GNU General Public License
! as published by the Free Software Foundation; either version 3
! of the License, or (at your option) any later version.
!
! HiPart is distributed in the hope that it will be useful,
! but WITHOUT ANY WARRANTY; without even the implied warranty of
! MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
! GNU General Public License for more details.
!
! You should have received a copy of the GNU General Public License
! along with this program; if not, see <http://www.gnu.org/licenses/>
!
! --


  subroutine gint1_fn_pF(a, a_a, p, out)
    intent(c) gint1_fn_pF
    intent(c)
    double precision intent(in) :: a(3), a_a, p(3)
    double precision intent(inout) :: out(7)
  end subroutine gint1_fn_pF

  subroutine gint1_fn_pD(a, a_a, p, out)
    intent(c) gint1_fn_pD
    intent(c)
    double precision intent(in) :: a(3), a_a, p(3)
    double precision intent(inout) :: out(5)
  end subroutine gint1_fn_pD

  subroutine gint1_fn_SP(a, a_a, p, out)
    intent(c) gint1_fn_SP
    intent(c)
    double precision intent(in) :: a(3), a_a, p(3)
    double precision intent(inout) :: out(4)
  end subroutine gint1_fn_SP

  subroutine gint1_fn_S(a, a_a, p, out)
    intent(c) gint1_fn_S
    intent(c)
    double precision intent(in) :: a(3), a_a, p(3)
    double precision intent(inout) :: out(1)
  end subroutine gint1_fn_S

  subroutine gint1_fn_P(a, a_a, p, out)
    intent(c) gint1_fn_P
    intent(c)
    double precision intent(in) :: a(3), a_a, p(3)
    double precision intent(inout) :: out(3)
  end subroutine gint1_fn_P

  subroutine gint1_fn_cD(a, a_a, p, out)
    intent(c) gint1_fn_cD
    intent(c)
    double precision intent(in) :: a(3), a_a, p(3)
    double precision intent(inout) :: out(6)
  end subroutine gint1_fn_cD

  subroutine gint1_fn_cF(a, a_a, p, out)
    intent(c) gint1_fn_cF
    intent(c)
    double precision intent(in) :: a(3), a_a, p(3)
    double precision intent(inout) :: out(10)
  end subroutine gint1_fn_cF
